#!/bin/bash
pushd "$(dirname "${BASH_SOURCE:-}")/.." > /dev/null;
set -euo pipefail;

if [ "${CNAME:-}" != "" ]; then
  # if CNAME is set in env, we use that.
  echo "Using provided CNAME: https://${CNAME}" 1>&2;
  true we good;
elif [ -e ./src/CNAME ]; then
  # otherwise if CNAME is set in ./src, we use that.
  CNAME="$(cat ./src/CNAME)";
  echo "Using saved CNAME: https://${CNAME}" 1>&2;
else
  # otherwise we pick a random name.
  CNAME="$(scripts/names.js).otter.academy"
  # we save it unless we're in a `template` folder.
  if [ "$(basename $(pwd))" != "template" ]; then
    echo "Generated and saved CNAME: https://${CNAME}" 1>&2;
    echo "${CNAME}" > ./src/CNAME;
  else
    echo "Generated temporary CNAME: https://${CNAME}" 1>&2;
  fi
fi

yarn pretty;
mkdir -p ./build;
rm -rf ./build/*;
yarn react-scripts build;

echo "${CNAME}" > ./build/CNAME;
