#!/bin/bash
set -euo pipefail;

yarn pretty;
mkdir -p ./build;
rm -rf ./build/*;
yarn react-scripts build;
rm -rf ./build/asset-manifest.json ./build/*/*/*LICENSE* ./build/*/*/*.map ./build/*manifest*.js ./build/service-worker.js;
echo \"$(basename \"${PWD}\").otter.academy\" > ./build/CNAME;
