#!/bin/bash
pushd "$(dirname "${BASH_SOURCE:-}")/.." > /dev/null;
set -euo pipefail;

yarn install --offline --frozen-lockfile;
yarn deploy:gh-pages:build;
git add src/CNAME;
git commit -m 'generated initial CNAME: https://$(cat src/CNAME)';

code --folder-uri . || echo 'You may want to install VS Code: https://code.visualstudio.com/' 1>&2;
yarn start;
