#!/bin/bash
set -meuo pipefail;
trap '
  killtree() {
      local _pid=$1;
      for _child in $(ps -o pid --no-headers --ppid ${_pid}); do
          killtree ${_child};
      done
      kill -TERM ${_pid};
  }
  killtree $(jobs -p)
' EXIT;
pushd "$(dirname "${BASH_SOURCE:-}")/.." > /dev/null;

yarn install --offline --frozen-lockfile;
yarn deploy:gh-pages:build;
git add --ignore-errors src/CNAME;
git commit -m "initial CNAME: https://$(cat src/CNAME)";
git config alias.merk '!MERKLE_TARGET=${PWD} '"${PWD}"'/scripts/merkle';

export PORT="$(( 3000 + ("$(date +1%s)" + "$(date +1%N)") % 7000 ))";
echo "Using port ${PORT}." 1>&2;

yarn start &
yarn_pid=$!;

bash --login &
bash_pid=$!;

code --new-window --wait . ./src/core/main.tsx || fg;

echo "Shutting down."; 1>&2;
