#!/bin/bash
set -euo pipefail;

git --no-pager log --graph --decorate -n 2;
echo;

read -p "$(tput bold)$(tput setaf 1)Press Y to normalize the merkle tree. Press N to quit. $(tput smul)" -n 1 -r;
echo "$(tput sgr 0)";
echo;
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    exit 1;
fi

env='export GIT_HEIGHT="$(printf %08d "$(git rev-list --count "${GIT_COMMIT:-HEAD}")")" ;\
  export GIT_COMMITTER_TIMESTAMP="$((1577836800 + 10 + 20 * (${GIT_HEIGHT} - 1) ))" ;\
  export GIT_COMMITTER_DATE="$(date -ud @"${GIT_COMMITTER_TIMESTAMP}")" ;\
  export GIT_COMMITTER_NAME="user" ;\
  export GIT_COMMITTER_EMAIL="\<user@localhost\>" ;\
  export GIT_AUTHOR_TIMESTAMP="$((1577836800 + 20 * (${GIT_HEIGHT} - 1) ))" ;\
  export GIT_AUTHOR_DATE="$(date -ud @"${GIT_AUTHOR_TIMESTAMP}")" ;\
  export GIT_AUTHOR_NAME="user" ;\
  export GIT_AUTHOR_EMAIL="\<user@localhost\>" ;\
  export GIT_TREE_HASH="$(git rev-parse --short=8 ${GIT_COMMIT:-HEAD}^{tree})" ;\
  export GIT_MESSAGE="${GIT_HEIGHT}-${GIT_TREE_HASH}" ;\
  true';

git filter-branch --force --env-filter "${env}" --msg-filter "${env}; echo \${GIT_MESSAGE}";
eval "$env";
git commit --amend --no-edit;

echo;
git --no-pager log --graph --decorate -n 2;
