#!/bin/bash
pushd "$(dirname "${BASH_SOURCE:-}")/.." > /dev/null;
set -euo pipefail;
shopt -s extglob globstar nullglob;
export GLOBIGNORE="**/node_modules/**";

jsonsort -p --arrays ./*.json ./src/!(data) ./public ./.github ./.vscode;
format-package --write ./**/package.json;
prettier --ignore-path .gitignore --write ./**/*.{ts,tsx,js,jsx,json,md,yml,yaml,html,css};
import-sort --ignore-path .gitignore --write ./**/*.{ts,tsx,js,jsx};
