#!/bin/bash
set -euo pipefail;

pushd "$(dirname "${BASH_SOURCE:-}")/.." > /dev/null;

mkdir -p ./src/data/scryfall/;

url="$(curl https://api.scryfall.com/bulk-data | jq '. |
  .data
  | map(select(.type == "oracle_cards"))
  | first
  | .download_uri
' --raw-output)";

echo "${url}";

curl "$url" | jq '
  map(
    select(.object == "card" and (.games | contains(["arena"])))
    | {
      name,
      layout,
      mana_cost,
      cmc,
      type_line,
      colors,
      set,
      rarity,
      oracle_text,
      standard_legal: .legalities.standard,
      image_uri: .image_uris.normal
    }
  )
' > ./src/data/scryfall/arena.json;
