{
  "name": "action",
  "on": ["push", "pull_request"],
  "jobs": {
    "job": {
      "runs-on": "ubuntu-latest",
      "steps": [
        { "uses": "actions/checkout@v2" },
        {
          "uses": "actions/setup-node@v2-beta",
          "with": { "node-version": "14.3.0" }
        },
        { "run": "yarn install" },
        { "run": "yarn pretty" },
        { "run": "yarn build" },
        { "run": "git status" }
      ]
    }
  }
}
